import { TechCard } from "@/types/game";

export const ALL_TECH_CARDS: TechCard[] = [
  {
    id: "react",
    name: "React",
    category: "Frontend",
    cost: 2,
    level: 1,
    difficulty: 2,
    popularity: 3,
    performance: 2,
  },
  {
    id: "vue",
    name: "Vue.js",
    category: "Frontend",
    cost: 1,
    level: 1,
    difficulty: 1,
    popularity: 2,
    performance: 2,
  },
  {
    id: "express",
    name: "Express.js",
    category: "Backend",
    cost: 1,
    level: 1,
    difficulty: 1,
    popularity: 3,
    performance: 2,
  },
  {
    id: "django",
    name: "Django",
    category: "Backend",
    cost: 2,
    level: 1,
    difficulty: 2,
    popularity: 2,
    performance: 2,
  },
  {
    id: "tensorflow",
    name: "TensorFlow",
    category: "Machine Learning",
    cost: 3,
    level: 1,
    difficulty: 3,
    popularity: 3,
    performance: 3,
  },
  {
    id: "pytorch",
    name: "PyTorch",
    category: "Machine Learning",
    cost: 3,
    level: 1,
    difficulty: 2,
    popularity: 3,
    performance: 3,
  },
  {
    id: "fastapi",
    name: "FastAPI",
    category: "Backend",
    cost: 2,
    level: 1,
    difficulty: 1,
    popularity: 2,
    performance: 3,
  },
  {
    id: "jwt",
    name: "JWT",
    category: "Authentication",
    cost: 1,
    level: 1,
    difficulty: 1,
    popularity: 2,
    performance: 2,
  },
  {
    id: "redis",
    name: "Redis",
    category: "Data Store",
    cost: 2,
    level: 1,
    difficulty: 1,
    popularity: 3,
    performance: 3,
  },
  {
    id: "oauth",
    name: "OAuth",
    category: "Authentication",
    cost: 2,
    level: 1,
    difficulty: 3,
    popularity: 2,
    performance: 1,
  },
  {
    id: "nextjs",
    name: "Next.js",
    category: "Frontend",
    cost: 3,
    level: 1,
    difficulty: 3,
    popularity: 3,
    performance: 3,
  },
  {
    id: "threejs",
    name: "Three.js",
    category: "Frontend",
    cost: 2,
    level: 1,
    difficulty: 3,
    popularity: 1,
    performance: 1,
  },
  {
    id: "websocket",
    name: "WebSocket",
    category: "Communication",
    cost: 2,
    level: 1,
    difficulty: 2,
    popularity: 2,
    performance: 3,
  },
];
