import { TechCard } from "../types";

export const ALL_TECH_CARDS: TechCard[] = [
  {
    id: "react",
    name: "React",
    category: "Frontend",
    cost: 2,
    level: 1,
    difficulty: 2,
    popularity: 3,
    performance: 2,
    icon: "/tech_icons/react.svg",
  },
  {
    id: "vue",
    name: "Vue.js",
    category: "Frontend",
    cost: 1,
    level: 1,
    difficulty: 1,
    popularity: 2,
    performance: 2,
    icon: "/tech_icons/vuejs.svg",
  },
  {
    id: "express",
    name: "Express.js",
    category: "Backend",
    cost: 1,
    level: 1,
    difficulty: 1,
    popularity: 3,
    performance: 2,
    icon: "/tech_icons/express.svg",
  },
  {
    id: "django",
    name: "Django",
    category: "Backend",
    cost: 2,
    level: 1,
    difficulty: 2,
    popularity: 2,
    performance: 2,
    icon: "/tech_icons/django.svg",
  },
  {
    id: "tensorflow",
    name: "TensorFlow",
    category: "Other",
    cost: 3,
    level: 1,
    difficulty: 3,
    popularity: 3,
    performance: 3,
    icon: "/tech_icons/tensorflow.svg",
  },
  {
    id: "pytorch",
    name: "PyTorch",
    category: "Other",
    cost: 3,
    level: 1,
    difficulty: 2,
    popularity: 3,
    performance: 3,
    icon: "/tech_icons/pytorch.png",
  },
  {
    id: "fastapi",
    name: "FastAPI",
    category: "Backend",
    cost: 2,
    level: 1,
    difficulty: 1,
    popularity: 2,
    performance: 3,
    icon: "/tech_icons/fastapi.png",
  },
  {
    id: "jwt",
    name: "JWT",
    category: "Other",
    cost: 1,
    level: 1,
    difficulty: 1,
    popularity: 2,
    performance: 2,
    icon: "/tech_icons/jwt.png",
  },
  {
    id: "redis",
    name: "Redis",
    category: "Other",
    cost: 2,
    level: 1,
    difficulty: 1,
    popularity: 3,
    performance: 3,
    icon: "/tech_icons/radis.png",
  },
  {
    id: "oauth",
    name: "OAuth",
    category: "Other",
    cost: 2,
    level: 1,
    difficulty: 3,
    popularity: 2,
    performance: 1,
    icon: "/tech_icons/oauth.png",
  },
  {
    id: "nextjs",
    name: "Next.js",
    category: "Frontend",
    cost: 3,
    level: 1,
    difficulty: 3,
    popularity: 3,
    performance: 3,
    icon: "/tech_icons/nextjs.svg",
  },
  {
    id: "threejs",
    name: "Three.js",
    category: "Frontend",
    cost: 2,
    level: 1,
    difficulty: 3,
    popularity: 1,
    performance: 1,
    icon: "/tech_icons/threejs.png",
  },
  {
    id: "websocket",
    name: "WebSocket",
    category: "Other",
    cost: 2,
    level: 1,
    difficulty: 2,
    popularity: 2,
    performance: 3,
    icon: "/tech_icons/websocket.svg",
  },
];
